name: books_finder
description: A library to help on the search for books on google books api
version: 4.3.0
repository: https://github.com/bdlukaa/books_finder

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
